argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/iamryanmacdonald/homelab-dev
            revision: &revision main
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: *revision