argocd:
  global:
    domain: argocd.127-0-0-1.nip.io
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  redis:
    metrics: *metrics
  repoServer:
    metrics: *metrics 
argocd-apps:
  applicationsets:
    root:
      namespace: argocd
      generators:
        - git:
            repoURL: &repoURL https://github.com/iamryanmacdonald/homelab-dev
            revision: &revision main
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*
      template:
        metadata:
          name: '{{ path.basename }}'
        spec:
          destination:
            name: in-cluster
            namespace: '{{ path.basename }}'
          project: default # TODO
          source:
            repoURL: *repoURL
            path: '{{ path }}'
            targetRevision: *revision
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - ApplyOutOfSyncOnly=true
              - CreateNamespace=true
              - ServerSideApply=true